package br.edu.gamaesouza.intranet.utils;

public enum PaisEnum {

AfricadoSul("africa do Sul"),
Albania("Albania"),
Alemanha("Alemanha"),
Andorra("Andorra"),
Angola("Angola"),
Anguilla("Anguilla"),
Antigua("Antigua"),
ArabiaSaudita("Arabia Saudita"),
Argentina("Argentina"),
Armenia("Armenia"),
Aruba("Aruba"),
Australia("Australia"),
austria("austria"),
Azerbaijao("Azerbaijao"),
Bahamas("Bahamas"),
Bahrein("Bahrein"),
Bangladesh("Bangladesh"),
Barbados("Barbados"),
Belgica("Belgica"),
Benin("Benin"),
Bermudas("Bermudas"),
Botsuana("Botsuana"),
BRASIL("Brasil"),
BRUNEI("Brunei"),
Bulgaria("Bulgaria"),
BurkinaFasso("Burkina Fasso"),
botao("botao"),
CaboVerde("Cabo Verde"),
Camaroes("Camaroes"),
Camboja("Camboja"),
Canada("Canada"),
Cazaquistao("Cazaquistao"),
Chade("Chade"),
Chile("Chile"),
China("China"),
CidadeDoVaticano("Cidade do Vaticano"),
Colombia("Colombia"),
Congo("Congo"),
CoreiaDoSul("Coreia do Sul"),
CostaDoMarfim("Costa do Marfim"),
CostaRica("Costa Rica"),
Croacia("Croacia"),
Dinamarca("Dinamarca"),
Djibuti("Djibuti"),
Dominica("Dominica"),
EUA("EUA"),
Egito("Egito"),
ElSalvador("El Salvador"),
EmiradosArabes("Emirados arabes"),
Equador("Equador"),
Eritreia("Eritreia"),
Escocia("Escocia"),
Eslovaquia("Eslovaquia"),
Eslovenia("Eslovenia"),
Espanha("Espanha"),
Estonia("Estonia"),
Etiopia("Etiopia"),
Fiji("Fiji"),
Filipinas("Filipinas"),
Finlandia("Finlandia"),
Franca("Franca"),
Gabao("Gabao"),
Gambia("Gambia"),
Gana("Gana"),
Georgia("Georgia"),
Gibraltar("Gibraltar"),
Granada("Granada"),
Grecia("Grecia"),
Guadalupe("Guadalupe"),
Guam("Guam"),
Guatemala("Guatemala"),
Guiana("Guiana"),
GuianaFrancesa("Guiana Francesa"),
Guinebissau("Guine-bissau"),
Haiti("Haiti"),
Holanda("Holanda"),
Honduras("Honduras"),
HongKong("Hong Kong"),
Hungria("Hungria"),
Iemen("Iemen"),
IlhasCayman("Ilhas Cayman"),
IlhasCook("Ilhas Cook"),
IlhasCuracao("Ilhas Curacao"),
IlhasMarshall("Ilhas Marshall"),
IlhasTurksCaicos("Ilhas Turks & Caicos"),
IlhasVirgens("Ilhas Virgens (brit.)"),
IlhasVirgensamer("Ilhas Virgens(amer.)"),
IlhasWallieFutuna("Ilhas Wallis e Futuna"),
india("india"),
Indonesia("Indonesia"),
Inglaterra("Inglaterra"),
Irlanda("Irlanda"),
Islandia("Islandia"),
Israel("Israel"),
Italia("Italia"),
Jamaica("Jamaica"),
Japao("Japao"),
Jordania("Jordania"),
Kuwait("Kuwait"),
Latvia("Latvia"),
Libano("Libano"),
Liechtenstein("Liechtenstein"),
Lituania("Lituania"),
Luxemburgo("Luxemburgo"),
Macau("Macau"),
Macedonia("Macedonia"),
Madagascar("Madagascar"),
Malasia("Malasia"),
Malaui("Malaui"),
Mali("Mali"),
Malta("Malta"),
Marrocos("Marrocos"),
Martinica("Martinica"),
Mauritania("Mauritania"),
Mauritius("Mauritius"),
Mexico("Mexico"),
Moldova("Moldova"),
Monaco("Monaco"),
Montserrat("Montserrat"),
Nepal("Nepal"),
Nicaragua("Nicaragua"),
Niger("Niger"),
Nigeria("Nigeria"),
Noruega("Noruega"),
NovaCaledonia("Nova Caledonia"),
NovaZelandia("Nova Zelandia"),
Oma("Oma"),
Palau("Palau"),
Panama("Panama"),
PapuanovaGuine("Papua-nova Guine"),
Paquistao("Paquistao"),
Peru("Peru"),
PolinesiaFrancesa("Polinesia Francesa"),
Polonia("Polonia"),
PortoRico("Porto Rico"),
Portugal("Portugal"),
Qatar("Qatar"),
Quenia("Quenia"),
RepDominicana("Rep. Dominicana"),
RepTcheca("Rep. Tcheca"),
Reunion("Reunion"),
Romenia("Romenia"),
Ruanda("Ruanda"),
Russia("Russia"),
Saipan("Saipan"),
SamoaAmericana("Samoa Americana"),
Senegal("Senegal"),
SerraLeone("Serra Leone"),
Seychelles("Seychelles"),
Singapura("Singapura"),
Siria("Siria"),
SriLanka("Sri Lanka"),
StKittsNevis("St. Kitts & Nevis"),
StLucia("St. Lucia"),
StVincent("St. Vincent"),
Sudao("Sudao"),
Suecia("Suecia"),
Suica("Suica"),
Suriname("Suriname"),
Tailandia("Tailandia"),
Taiwan("Taiwan"),
Tanzania("Tanzania"),
Togo("Togo"),
TrinidadTobago("Trinidad & Tobago"),
Tunisia("Tunisia"),
Turquia("Turquia"),
Ucrania("Ucrania"),
Uganda("Uganda"),
Uruguai("Uruguai"),
Venezuela("Venezuela"),
Vietna("Vietna"),
Zaire("Zaire"),
Zambia("Zambia"),
Zimbabue("Zimbabue");


	private String name;

    private PaisEnum(String name) {
        this.name = name;
    }

    public String getName() {
        return name;
    }


}
